version: '3.8'

services:
  bot:
    container_name: mint-apex-bot
    build:
      dockerfile: Dockerfile
      context: '.'
    ports:
      - ${API_PORT}:${API_PORT}
      - ${WS_PORT}:${WS_PORT}
    volumes:
      - /app/node_modules
      - /app

  ipfs:
    image: 'ipfs/go-ipfs:v0.10.0'
    container_name: mint-apex-ipfs
    volumes:
      - ./ipfs/ipfs_staging:/export
      - ./ipfs/ipfs_data:/data/ipfs
    ports:
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/tcp
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/udp
      - 0.0.0.0:${IPFS_API}:${IPFS_API}
      - ${IPFS_LOCAL_GATEWAY}:${IPFS_LOCAL_GATEWAY}
      - 0.0.0.0:${IPFS_WS}:${IPFS_WS}
    environment:
      IPFS_PROFILE: 'server'
      IPFS_PATH: '/data/ipfs'
