version: '3.8'

services:
  mongo:
    image: 'mongo'
    container_name: xaddress_manager_db
    restart: always
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'super_secret_password'

  ipfs:
    image: 'ipfs/go-ipfs:v0.10.0'
    container_name: ipfs
    volumes:
      - ./ipfs/ipfs_staging:/export
      - ./ipfs/ipfs_data:/data/ipfs
    ports:
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/tcp
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/udp
      - ${IPFS_API}:${IPFS_API}
      - ${IPFS_LOCAL_GATEWAY}:${IPFS_LOCAL_GATEWAY}
      - 0.0.0.0:${IPFS_WS}:${IPFS_WS}
    environment:
      IPFS_PROFILE: 'server'
      IPFS_PATH: '/data/ipfs'
