version: '3.8'

services:
  mongo:
    image: 'mongo'
    container_name: mintbot-db
    restart: always
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'super_secret_password'

  ipfs:
    image: 'ipfs/go-ipfs:v0.10.0'
    container_name: mintbot-ipfs
    volumes:
      - ./ipfs/ipfs_staging:/export
      - ./ipfs/ipfs_data:/data/ipfs
    ports:
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/tcp
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}/udp
      - 0.0.0.0:${IPFS_API}:${IPFS_API}
      - ${IPFS_LOCAL_GATEWAY}:${IPFS_LOCAL_GATEWAY}
      - 0.0.0.0:${IPFS_WS}:${IPFS_WS}
    environment:
      IPFS_PROFILE: 'server'
      IPFS_PATH: '/data/ipfs'

  api:
    container_name: mintbot-api
    build:
      dockerfile: Dockerfile.api
      context: '.'
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - /app/node_modules
      - /app
    environment:
      API_PORT: ${API_PORT}
      API_SECRET: ${API_SECRET}

  bot:
    container_name: mintbot-bot
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - /app/node_modules
      - /app
    environment:
      API_PORT: ${API_PORT}
      API_SECRET: ${API_SECRET}
